### ISSUE TITLE
Finding the weather API ( mode of transportation - car)

### ISSUE THREAD

**Issue by Hirvashah2112** [ygoralmeida1993/Group-4-project#25]

**Comment by Pujaholy** [comment]
I have found the AccuWeather for weather API. The link is: https://developer.accuweather.com/apis
Among the APIs listed in the link, I think only the location API will do. It gives the weather feeds according to location input. The link: https://developer.accuweather.com/accuweather-locations-api/apis

**Comment by Pujaholy** [comment]
AccuWeather API free version give feeds for 5 days only. So I will use either DarkSky or Weather2020 API because they are free. The links are: 1) Weather2020- https://rapidapi.com/Weather2020/api/weather/endpoints
2) DarkSky- https://darksky.net/dev
Testing link: https://api.darksky.net/forecast/13e04b25432c5d707a0a3c080d15a5b7/37.8267,-122.4233
Secret key: 13e04b25432c5d707a0a3c080d15a5b7

**Comment by Pujaholy** [comment]
DarkSky is the best API we can use.
